// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"api_new/modules/invoice/orm/models"
)

type InvoiceInput struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type Invoices struct {
	Count int               `json:"count"`
	List  []*models.Invoice `json:"list"`
}

type QueryInvoice struct {
	Code        *string `json:"code"`
	Description *string `json:"description"`
}
