apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: go-api # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: go-api
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: go-api # Selects any Pod with labels `app=api-modules`
  ports:
    - name: http
      port: 7777
      targetPort: 7777
