version: '3'
services:
  app:
    container_name: api_container
    build: .
    ports: 
      - "7777:7777"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on: 
      - db
    networks: 
      - fullstack

  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_SERVER_USER}  
      - POSTGRES_PASSWORD=${DB_SERVER_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_SERVER_HOST}
    ports:
     - '5433:5432'
    volumes: 
      - database_postgres:/var/lib/postgresql/data
    networks: 
      - fullstack

  pdadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped
  
volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge