apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "ctbserver"
  DB_SERVER_HOST: fullstack-postgres
  DB_SERVER_PORT: "5432"
  DB_DRIVER: "postgres"
  DB_SERVER_USER: "postgres"
  DB_SERVER_PASS: "admin"
  DB_NAME: "ctbwebmaster"
  