// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"api_new/modules/user/orm/models"
)

type DatabaseInput struct {
	RegistrationID int    `json:"registrationId"`
	ExpiryDate     int    `json:"expiryDate"`
	DatabaseName   string `json:"databaseName"`
}

type QueryUser struct {
	Email string `json:"email"`
}

type RegistrationInput struct {
	CompanyName   string `json:"companyName"`
	PhoneNo       string `json:"phoneNo"`
	FaxNo         string `json:"faxNo"`
	Website       string `json:"website"`
	StreetAddress string `json:"streetAddress"`
}

type UserInfo struct {
	Email        string `json:"email"`
	Fullname     string `json:"fullname"`
	Nickname     string `json:"nickname"`
	AvatarBase64 string `json:"avatarBase64"`
}

type UserInput struct {
	Email         string `json:"email"`
	Fullname      string `json:"fullname"`
	Nickname      string `json:"nickname"`
	Password      string `json:"password"`
	AvatarBase64  string `json:"avatarBase64"`
	RoleID        string `json:"roleID"`
	InUseDatabase string `json:"inUseDatabase"`
}

type Users struct {
	Count int            `json:"count"`
	List  []*models.User `json:"list"`
}
