// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"api_new/modules/stock/orm/models"
)

type QueryStock struct {
	Code        *string `json:"code"`
	Description *string `json:"description"`
}

type StockInput struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type Stocks struct {
	Count int             `json:"count"`
	List  []*models.Stock `json:"list"`
}
