// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	Authtoken string      `json:"authtoken"`
	User      *UserOutput `json:"user"`
}

type RegisterInput struct {
	Email         string `json:"email"`
	Fullname      string `json:"fullname"`
	Nickname      string `json:"nickname"`
	Password      string `json:"password"`
	AvatarBase64  string `json:"avatarBase64"`
	CompanyName   string `json:"companyName"`
	PhoneNo       string `json:"phoneNo"`
	FaxNo         string `json:"faxNo"`
	Website       string `json:"website"`
	StreetAddress string `json:"streetAddress"`
}

type RegisterResult struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	Fullname      string `json:"fullname"`
	Nickname      string `json:"nickname"`
	AvatarBase64  string `json:"avatarBase64"`
	CompanyName   string `json:"companyName"`
	PhoneNo       string `json:"phoneNo"`
	FaxNo         string `json:"faxNo"`
	Website       string `json:"website"`
	StreetAddress string `json:"streetAddress"`
	InUseDatabase string `json:"inUseDatabase"`
}

type UserOutput struct {
	ID                                 string   `json:"id"`
	Email                              string   `json:"email"`
	PhoneNumber                        string   `json:"phoneNumber"`
	Fullname                           string   `json:"fullname"`
	Nickname                           string   `json:"nickname"`
	AvatarBase64                       string   `json:"avatarBase64"`
	RoleID                             string   `json:"roleID"`
	StartDate                          *int     `json:"startDate"`
	MinDailyUnitPointsRequirement      *float64 `json:"minDailyUnitPointsRequirement"`
	StandardNumberOfWorkingDaysPerWeek *float64 `json:"standardNumberOfWorkingDaysPerWeek"`
	Config                             string   `json:"config"`
}
